version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: vendor_shop_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vendor_shop_db
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    ports:
      - "5432:5432" 
    volumes:
      - "./volume:/var/lib/postgresql/data"